Repository BiahLages/games, pull requests merged in 2022-11, with the labels that each got.

#6 fix: readme
  README.md
Labels: documentation

#10 Fix: contexts and components
  README.md
  package.json
  src/App.css
  src/App.tsx
  src/assets/icons/index.tsx
  src/assets/styles/constants.ts
  src/components/AllGames.tsx
  src/components/Input/index.tsx
  src/components/Input/styles.ts
  src/components/Login/index.tsx
  src/components/Login/styles.ts
  src/components/Menu/index.tsx
  src/components/Menu/styles.ts
  src/components/Sidebar.tsx
  src/contexts/AccountContext.tsx
  src/contexts/FavoritesContext.tsx
  src/contexts/GamesContext.tsx
  src/contexts/OrderSettingsContext.tsx
  src/contexts/index.tsx
  src/helpers/Api.ts
  src/index.css
  src/pages/Home/index.tsx
  src/pages/Home/styles.ts
  src/pages/Login/index.tsx
  src/pages/Login/styles.ts
  src/pages/Profile/index.tsx
  src/pages/Profile/styles.ts
  src/pages/Settings/index.tsx
  src/pages/Settings/styles.ts
  src/pages/styles.ts
  src/routers/index.tsx
  src/types/interfaces/order.ts
Labels: enhancement

#20 version
  README.md
Labels: bug

#22 fix: colors
  src/assets/styles/colors.ts
  src/types/interfaces/system.ts
Labels: bug

#24 Fix: Routes to vercel and advanced search
  src/contexts/GamesContext.tsx
  vercel.json
Labels: bug

#26 Feat: Profiles
  src/assets/icons/edit.png
  src/assets/icons/formEdit.png
  src/assets/icons/index.tsx
  src/assets/icons/pencil.svg
  src/assets/icons/trash.png
  src/assets/styles/colors.ts
  src/components/Profile/index.tsx
  src/components/Profiles/index.tsx
  src/contexts/GamesContext.tsx
  src/contexts/ProfilesContext.tsx
  src/contexts/index.tsx
  src/images.d.ts
  src/index.css
  src/pages/Profile/index.tsx
  src/pages/styles.ts
  src/types/interfaces/profiles.ts
  tsconfig.json
Labels: enhancement

#27 Version 1.1
  src/assets/icons/edit.png
  src/assets/icons/formEdit.png
  src/assets/icons/index.tsx
  src/assets/icons/pencil.svg
  src/assets/icons/trash.png
  src/assets/styles/colors.ts
  src/components/Profile/index.tsx
  src/components/Profiles/index.tsx
  src/contexts/GamesContext.tsx
  src/contexts/ProfilesContext.tsx
  src/contexts/index.tsx
  src/images.d.ts
  src/index.css
  src/pages/Profile/index.tsx
  src/pages/styles.ts
  src/types/interfaces/profiles.ts
  tsconfig.json
Labels: enhancement

#29 fix indentation
  src/assets/images/gamedevs.png
  src/components/Profiles/index.tsx
  src/contexts/GamesContext.tsx
  src/pages/Settings/index.tsx
Labels: enhancement

#28 Page Login
  src/components/Gate/index.tsx
  src/components/Gate/styles.ts
  src/components/Input/index.tsx
  src/components/Input/styles.ts
  src/components/Login/styles.ts
  src/components/Profile/index.tsx
  src/pages/Login/index.tsx
Labels: documentation

#33 fix: register CPF
  README.md
  src/components/Gate/index.tsx
  src/pages/Settings/index.tsx
  src/routers/index.tsx
  src/types/interfaces/users.ts
Labels: enhancement

#34 Producao
  README.md
  src/components/Gate/index.tsx
  src/routers/index.tsx
  src/types/interfaces/users.ts
Labels: enhancement

#39 Feat: ConfigUserContext and some fixes
  src/components/Gate/index.tsx
  src/contexts/ConfigUserContext.tsx
  src/contexts/index.tsx
  src/pages/Settings/index.tsx
  src/types/interfaces/configUser.ts
Labels: enhancement

#42 fix: readme hyperlink
  README.md
Labels: documentation

#43 fix: readme hyperlinks
  README.md
Labels: documentation

#47 Feat: create profile
  src/components/Profiles/index.tsx
  src/contexts/ProfilesContext.tsx
  src/types/interfaces/profiles.ts
Labels: enhancement

#50 Feat: logout and protect handler
  src/components/Menu/index.tsx
  src/components/Profiles/index.tsx
  src/contexts/ConfigUserContext.tsx
  src/contexts/ProfilesContext.tsx
  src/pages/Profile/index.tsx
  src/pages/Settings/index.tsx
  src/types/interfaces/configUser.ts
Labels: enhancement

#52 Fix: double reload at open
  src/contexts/AccountContext.tsx
  src/pages/Login/index.tsx
  src/routers/index.tsx
Labels: Fix

#53 Producao
  src/contexts/AccountContext.tsx
  src/pages/Login/index.tsx
  src/routers/index.tsx
Labels: Deploy

#58 implementation page profiles
  src/components/Profile/index.tsx
  src/components/Profile/style.ts
  src/components/Profiles/index.tsx
  src/components/Profiles/style.ts
  src/pages/Profile/styles.ts
Labels: documentation

#57 new file - Card component
  .gitignore
  src/components/Card/index.tsx
Labels: enhancement

#59 Implementation page profile
  src/components/Profile/index.tsx
  src/components/Profile/style.ts
  src/components/Profiles/index.tsx
  src/components/Profiles/style.ts
  src/pages/Profile/styles.ts
Labels: documentation

#60 Fix: component menu and login
  src/assets/styles/colors.ts
  src/assets/styles/mixins.ts
  src/components/Menu/index.tsx
  src/components/Menu/styles.ts
  src/contexts/AccountContext.tsx
  src/routers/index.tsx
  src/types/interfaces/system.ts
Labels: Fix

#61 Producao
  .gitignore
  src/components/Card/index.tsx
Labels: enhancement

#65 Fix: Profile
  src/components/Menu/styles.ts
  src/components/Profile/index.tsx
  src/components/Profile/style.ts
  src/components/Profiles/index.tsx
  src/contexts/AccountContext.tsx
  src/types/interfaces/system.ts
Labels: Fix

#67 update Card - adicao de styles e informacoes
  src/components/Card/index.tsx
  src/components/Card/styles.tsx
Labels: enhancement

#68 fix: some bugs
  src/components/Menu/index.tsx
  src/components/Profiles/index.tsx
  src/types/interfaces/system.ts
  src/types/types.ts
Labels: Fix

#70 add form create profile
  src/components/Profiles/index.tsx
  src/components/Profiles/style.ts
  src/pages/Profile/styles.ts
Labels: Bug

#71 feat: gameComponent
  src/components/Card/index.tsx
  src/pages/Home/index.tsx
  src/types/interfaces/games.ts
Labels: enhancement, Fix

#72 Feat: component card and profile fixes
  public/index.html
  src/components/Card/index.tsx
  src/components/Card/styles.tsx
  src/components/Menu/index.tsx
  src/components/Menu/styles.ts
  src/components/Profile/index.tsx
  src/components/Profile/style.ts
  src/components/Profiles/index.tsx
  src/components/Profiles/style.ts
  src/contexts/AccountContext.tsx
  src/contexts/ConfigUserContext.tsx
  src/pages/Home/index.tsx
  src/pages/Profile/styles.ts
  src/pages/Settings/index.tsx
  src/types/interfaces/configUser.ts
  src/types/interfaces/games.ts
  src/types/interfaces/system.ts
  src/types/types.ts
Labels: enhancement, Deploy, Fix

#73 Fix: styled at profile
  src/components/Profile/index.tsx
  src/components/Profile/style.ts
Labels: enhancement, Fix

#74 Fixes at profile
  src/components/Profile/index.tsx
  src/components/Profile/style.ts
Labels: enhancement, Deploy

#75 Feat: Profiles
  src/components/Card/styles.tsx
  src/components/Profile/index.tsx
  src/components/Profile/style.ts
  src/components/Profiles/index.tsx
  src/components/Profiles/style.ts
  src/contexts/ProfilesContext.tsx
  src/pages/Home/index.tsx
  src/types/interfaces/games.ts
  src/types/interfaces/system.ts
  src/types/types.ts
Labels: enhancement

#76 Profiles
  src/components/Card/styles.tsx
  src/components/Profile/index.tsx
  src/components/Profile/style.ts
  src/components/Profiles/index.tsx
  src/components/Profiles/style.ts
  src/contexts/ProfilesContext.tsx
  src/pages/Home/index.tsx
  src/types/interfaces/games.ts
  src/types/interfaces/system.ts
  src/types/types.ts
Labels: enhancement, Deploy

#77 feat:
  src/contexts/ConfigUserContext.tsx
  src/types/interfaces/configUser.ts
  src/types/interfaces/users.ts
  src/types/types.ts
Labels: Deploy

#78 Fix: configUser settings
  src/contexts/ConfigUserContext.tsx
  src/types/interfaces/configUser.ts
  src/types/interfaces/users.ts
  src/types/types.ts
Labels: Fix

#80 Fix: menu profile picture
  src/components/Menu/index.tsx
  src/components/Menu/styles.ts
  src/contexts/ProfilesContext.tsx
  src/types/interfaces/profiles.ts
Labels: enhancement, Fix

#81 Fix: menu profile picture
  src/components/Menu/index.tsx
  src/components/Menu/styles.ts
  src/contexts/ProfilesContext.tsx
  src/types/interfaces/profiles.ts
Labels: enhancement, Deploy

#83 feat: created page recover password
  src/pages/Recover/index.tsx
  src/routers/index.tsx
Labels: Deploy

#85 Feat: Game Page
  src/components/Card/index.tsx
  src/components/Card/styles.tsx
  src/components/Game/index.tsx
  src/components/Game/styles.tsx
  src/contexts/GamesContext.tsx
  src/pages/GamePage/index.tsx
  src/pages/GamePage/styles.ts
  src/routers/index.tsx
  src/types/interfaces/games.ts
Labels: enhancement

#86 Feat: Game page
  src/components/Card/index.tsx
  src/components/Card/styles.tsx
  src/components/Game/index.tsx
  src/components/Game/styles.tsx
  src/contexts/GamesContext.tsx
  src/pages/GamePage/index.tsx
  src/pages/GamePage/styles.ts
  src/routers/index.tsx
  src/types/interfaces/games.ts
Labels: Deploy

#88 Fix: top rated games order
  src/contexts/OrderSettingsContext.tsx
Labels: Fix

#89 Fix: Top rated games order
  src/contexts/OrderSettingsContext.tsx
Labels: Deploy, Fix

#94 feat: home
  src/components/Games/index.tsx
  src/pages/Home/index.tsx
Labels: enhancement

#98 Fix: Responsive
  src/components/Game/styles.tsx
  src/components/Menu/index.tsx
  src/components/MenuUpdateAdmin/index.tsx
  src/components/MenuUpdateChoice/index.tsx
  src/components/MenuUpdateChoice/style.ts
  src/components/MenuUpdateUser/index.tsx
  src/components/Settings/index.tsx
  src/contexts/ConfigUserContext.tsx
  src/pages/Setting/index.tsx
  src/pages/Setting/styles.ts
  src/pages/Settings/index.tsx
  src/routers/index.tsx
  src/types/interfaces/configUser.ts
Labels: enhancement, Deploy

#99 feat: basic home
  src/components/Card/styles.tsx
  src/components/Favorites/index.tsx
  src/components/Genres/index.tsx
  src/components/TopRated/index.tsx
  src/pages/Home/index.tsx
Labels: enhancement

#101 Feat: Loading page
  .gitignore
  src/assets/images/loaderI.gif
  src/assets/images/loaderII.gif
  src/assets/images/loaderIII.gif
  src/assets/images/loaderIV.gif
  src/images.d.ts
  src/pages/LoadingUser/index.tsx
Labels: enhancement

#102 feat: arrows (not ready)
  src/components/Genres/index.tsx
  src/components/Genres/styles.ts
  src/components/TopRated/index.tsx
  src/components/TopRated/styles.ts
  src/contexts/GamesContext.tsx
  src/contexts/OrderSettingsContext.tsx
  src/types/interfaces/games.ts
Labels: enhancement, Fix

#103 Fix: Eslint update settings
  .eslintrc.js
  .gitignore
  src/components/Card/styles.tsx
  src/components/Favorites/index.tsx
  src/components/Game/index.tsx
  src/components/Game/styles.tsx
  src/components/Genres/index.tsx
  src/components/Genres/styles.ts
  src/components/TopRated/index.tsx
  src/components/TopRated/styles.ts
  src/contexts/AccountContext.tsx
  src/contexts/ConfigUserContext.tsx
  src/contexts/GamesContext.tsx
  src/contexts/ProfilesContext.tsx
  src/pages/GamePage/index.tsx
  src/pages/Home/index.tsx
  src/pages/LoadingUser/index.tsx
  src/pages/Profile/styles.ts
  tsconfig.json
Labels: Fix

#104 fix: bug fav
  src/components/Favorites/index.tsx
  src/contexts/GamesContext.tsx
Labels: Fix

#105 Fix: game context
  src/components/Favorites/index.tsx
  src/components/Menu/index.tsx
  src/contexts/GamesContext.tsx
Labels: Fix

#106 Fix: home
  .eslintrc.js
  src/assets/images/loaderI.gif
  src/assets/images/loaderII.gif
  src/assets/images/loaderIII.gif
  src/assets/images/loaderIV.gif
  src/components/Card/styles.tsx
  src/components/Favorites/index.tsx
  src/components/Game/index.tsx
  src/components/Game/styles.tsx
  src/components/Games/index.tsx
  src/components/Genres/index.tsx
  src/components/Genres/styles.ts
  src/components/Menu/index.tsx
  src/components/TopRated/index.tsx
  src/components/TopRated/styles.ts
  src/contexts/AccountContext.tsx
  src/contexts/ConfigUserContext.tsx
  src/contexts/GamesContext.tsx
  src/contexts/OrderSettingsContext.tsx
  src/contexts/ProfilesContext.tsx
  src/images.d.ts
  src/pages/GamePage/index.tsx
  src/pages/Home/index.tsx
  src/pages/LoadingUser/index.tsx
  src/pages/Profile/styles.ts
  src/types/interfaces/games.ts
  tsconfig.json
Labels: enhancement, Deploy, Fix

#108 Fix: genres
  src/components/Genres/index.tsx
Labels: Fix

#109 Fix: Menu settings
  src/components/Favorites/index.tsx
  src/components/MenuUpdateUser/index.tsx
  src/components/MenuUpdateUser/styles.ts
Labels: Fix

#110 Fix: Menu settings
  src/components/MenuUpdateUser/index.tsx
  src/components/MenuUpdateUser/styles.ts
Labels: Deploy, Fix

#113 fix: error password function handleUpdateUser
  src/contexts/ConfigUserContext.tsx
Labels: Bug

#114 feat: style page recover
  src/pages/Recover/index.tsx
Labels: Deploy

#116 Fix: unique route to gamepage
  src/components/Menu/index.tsx
  src/contexts/AccountContext.tsx
  src/contexts/ProfilesContext.tsx
  src/pages/GamePage/index.tsx
  src/routers/index.tsx
  src/types/types.ts
Labels: Fix

#117 Fix: unique router and userContext
  src/components/Menu/index.tsx
  src/components/MenuUpdateUser/index.tsx
  src/components/MenuUpdateUser/styles.ts
  src/components/Modal/index.tsx
  src/components/Modal/styles.ts
  src/components/Overlay/index.tsx
  src/components/Overlay/styles.ts
  src/contexts/AccountContext.tsx
  src/contexts/ConfigUserContext.tsx
  src/contexts/ProfilesContext.tsx
  src/pages/GamePage/index.tsx
  src/pages/Recover/index.tsx
  src/routers/index.tsx
  src/types/interfaces/configUser.ts
  src/types/types.ts
Labels: Deploy, Fix

#118 feat: style pages para forgot password
  src/components/Gate/index.tsx
  src/components/Gate/styles.ts
  src/pages/Forgot/index.tsx
  src/pages/Forgot/style.ts
  src/pages/Recover/index.tsx
  src/routers/index.tsx
Labels: enhancement

#119 fix: indentation
  src/components/Modal/index.tsx
  src/components/Modal/styles.ts
  src/components/Overlay/index.tsx
  src/components/Overlay/styles.ts
  src/routers/index.tsx
Labels: Deploy

#123 fix: indentation
  src/components/TopRated/index.tsx
  src/contexts/GamesContext.tsx
  src/types/interfaces/games.ts
Labels: enhancement, Fix

#124 fix: indentation and some fixes
  package.json
  src/App.tsx
  src/components/MenuUpdateUser/index.tsx
  src/components/TopRated/index.tsx
  src/contexts/GamesContext.tsx
  src/types/interfaces/games.ts
  src/utils/validation.tools.ts
  yarn.lock
Labels: Fix

#125 fix: menuUpdateUser component centering
  src/components/MenuUpdateUser/index.tsx
  src/pages/Setting/index.tsx
  src/pages/Setting/styles.ts
  src/types/interfaces/configUser.ts
Labels: Fix

#128 feat: genres
  .eslintrc.js
  src/components/Genres/index.tsx
  src/components/TopRated/index.tsx
  src/contexts/GamesContext.tsx
  src/types/interfaces/games.ts
Labels: enhancement

#129 fix: error iframe
  src/contexts/GamesContext.tsx
Labels: Bug

#135 fix: genre "ok"
  src/components/Genres/index.tsx
  src/contexts/GamesContext.tsx
Labels: Fix

#137 Fix: blank profiles
  src/components/Profiles/index.tsx
  src/contexts/ProfilesContext.tsx
  src/pages/LoadingUser/index.tsx
  src/pages/Profile/index.tsx
  src/routers/index.tsx
Labels: Fix

#138 Fix: home and blank profiles
  src/components/CreateUpGame/index.tsx
  src/components/CreateUpGame/style.ts
  src/components/Genres/index.tsx
  src/components/Profiles/index.tsx
  src/contexts/AdminGamesContext.tsx
  src/contexts/GamesContext.tsx
  src/contexts/ProfilesContext.tsx
  src/contexts/index.tsx
  src/pages/LoadingUser/index.tsx
  src/pages/Profile/index.tsx
  src/routers/index.tsx
  src/types/interfaces/games.ts
Labels: enhancement, Deploy

#139 feat: star score
  src/components/Game/index.tsx
  src/components/Game/styles.tsx
  src/types/interfaces/games.ts
Labels: enhancement

#140 Fix: size and img src - Card
  src/components/Card/index.tsx
  src/components/Card/styles.tsx
  src/components/Game/index.tsx
  src/components/Game/styles.tsx
  src/types/interfaces/games.ts
Labels: Deploy

#141 fix: layout
  src/assets/styles/global.ts
  src/components/CreateUpGame/index.tsx
  src/components/CreateUpGame/style.ts
  src/components/Game/index.tsx
  src/components/Game/styles.tsx
  src/components/Gate/index.tsx
  src/contexts/AdminGamesContext.tsx
  src/pages/styles.ts
  src/types/interfaces/games.ts
Labels: Fix

#145 update
  src/components/CreateUpGame/index.tsx
  src/components/CreateUpGame/style.ts
  src/components/Game/index.tsx
  src/components/Game/styles.tsx
  src/components/Settings/index.tsx
  src/pages/styles.ts
Labels: Deploy

#146 Fix: typescript and sintax
  .eslintrc.js
  src/assets/styles/global.ts
  src/components/Card/index.tsx
  src/components/Card/styles.tsx
  src/components/CreateUpGame/style.ts
  src/components/Game/index.tsx
  src/components/Game/styles.tsx
  src/components/Menu/index.tsx
  src/contexts/GamesContext.tsx
  src/pages/Forgot/index.tsx
  src/pages/GamePage/styles.ts
  src/pages/Home/index.tsx
  src/pages/Home/styles.ts
  src/pages/Recover/index.tsx
  src/pages/styles.ts
Labels: Fix

#147 fix: Load profiles
  src/components/Genres/index.tsx
  src/components/Menu/index.tsx
  src/contexts/AccountContext.tsx
  src/contexts/ProfilesContext.tsx
  src/pages/LoadingUser/index.tsx
  src/types/interfaces/profiles.ts
Labels: Fix

#148 Update feature: menu profile
  .eslintrc.js
  src/components/Menu/index.tsx
  src/contexts/ProfilesContext.tsx
  src/pages/LoadingUser/index.tsx
Labels: Fix

#149 Fix: CreateFormModal
  src/components/CreateUpGame/index.tsx
  src/components/CreateUpGame/style.ts
Labels: Documentation

#150 Fix: The worst front-end enemy ever
  src/contexts/ConfigUserContext.tsx
Labels: enhancement, Fix

#153 fix: menu and modals
  .eslintrc.js
  .gitignore
  src/assets/styles/global.ts
  src/components/Card/index.tsx
  src/components/Card/styles.tsx
  src/components/CreateUpGame/index.tsx
  src/components/CreateUpGame/style.ts
  src/components/Game/index.tsx
  src/components/Game/styles.tsx
  src/components/Genres/index.tsx
  src/components/Menu/index.tsx
  src/components/Menu/styles.ts
  src/components/Profile/style.ts
  src/contexts/AccountContext.tsx
  src/contexts/ConfigUserContext.tsx
  src/contexts/GamesContext.tsx
  src/contexts/ProfilesContext.tsx
  src/pages/Forgot/index.tsx
  src/pages/GamePage/index.tsx
  src/pages/GamePage/styles.ts
  src/pages/Home/index.tsx
  src/pages/Home/styles.ts
  src/pages/LoadingUser/index.tsx
  src/pages/Profile/styles.ts
  src/pages/Recover/index.tsx
  src/pages/styles.ts
  src/types/interfaces/profiles.ts
Labels: Fix

#152 update - Card design (img and title)
  src/components/Card/index.tsx
  src/components/Card/styles.tsx
Labels: enhancement

#155 update
  .eslintrc.js
  src/components/Card/index.tsx
  src/components/Card/styles.tsx
Labels: Deploy

#156 fix: more time to login
  src/pages/LoadingUser/index.tsx
Labels: Fix

#160 add/update - Cards styles and home layout
  src/components/Favorites/index.tsx
  src/components/Favorites/styles.tsx
  src/components/Genres/index.tsx
  src/components/Genres/styles.ts
  src/components/TopRated/index.tsx
  src/components/TopRated/styles.tsx
  src/pages/styles.ts
Labels: enhancement

#165 feat: favorites and genres
  src/components/Favorites/index.tsx
  src/components/Genres/index.tsx
  src/contexts/FavoritesContext.tsx
  src/contexts/GamesContext.tsx
  src/contexts/OrderSettingsContext.tsx
  src/types/interfaces/order.ts
Labels: Bug, enhancement, Fix

#163 updates - imgs fixes
  src/components/Card/styles.tsx
  src/components/Favorites/index.tsx
  src/components/Favorites/styles.tsx
  src/components/Genres/index.tsx
  src/components/Genres/styles.ts
  src/components/TopRated/index.tsx
  src/components/TopRated/styles.tsx
  src/pages/styles.ts
Labels: enhancement

#167 Fix: CRUD games
  src/components/CreateUpGame/index.tsx
  src/components/Favorites/index.tsx
  src/contexts/AdminGamesContext.tsx
Labels: Fix

#168 Deploy
  src/assets/icons/addGame.png
  src/assets/icons/triangulo.png
  src/components/Card/styles.tsx
  src/components/CreateUpGame/index.tsx
  src/components/Favorites/index.tsx
  src/components/Favorites/styles.tsx
  src/components/Genres/index.tsx
  src/components/Genres/styles.ts
  src/components/MenuUpdateChoice/index.tsx
  src/components/MenuUpdateChoice/style.ts
  src/components/TopRated/index.tsx
  src/components/TopRated/styles.tsx
  src/contexts/AdminGamesContext.tsx
  src/pages/styles.ts
  src/utils/blankgame.tools.ts
Labels: Deploy

#169 feat: home style
  src/components/Favorites/index.tsx
  src/components/Favorites/styles.tsx
  src/components/Genres/index.tsx
  src/components/Genres/styles.ts
  src/components/TopRated/index.tsx
  src/components/TopRated/styles.tsx
Labels: enhancement, Fix

#171 updates - ranking & img sizes changing (px to rem)
  src/components/Card/index.tsx
  src/components/Card/styles.tsx
Labels: enhancement

#172 feat: select
  src/components/CreateUpGame/index.tsx
Labels: enhancement

#175 fix: partial favorites
  src/components/Game/index.tsx
  src/contexts/FavoritesContext.tsx
  src/types/interfaces/api.ts
Labels: Bug

#177 fix: profiles without loading
  src/components/Profiles/index.tsx
Labels: Bug

#178 Deploy
  src/components/CreateUpGame/index.tsx
  src/components/Game/index.tsx
  src/components/Profiles/index.tsx
  src/contexts/FavoritesContext.tsx
  src/contexts/ProfilesContext.tsx
  src/types/interfaces/api.ts
Labels: Deploy

#182 fix: load favorites
  src/components/Profile/index.tsx
  src/contexts/FavoritesContext.tsx
  src/types/interfaces/favorites.ts
Labels: Deploy

#185 Final countdown
  src/components/CreateUpGame/index.tsx
  src/components/Favorites/index.tsx
  src/components/Favorites/styles.tsx
  src/components/Game/index.tsx
  src/components/TopRated/index.tsx
  src/contexts/AdminGamesContext.tsx
  src/contexts/ConfigUserContext.tsx
  src/contexts/FavoritesContext.tsx
  src/contexts/GamesContext.tsx
  src/pages/Forgot/index.tsx
  src/pages/GamePage/index.tsx
  src/pages/Profile/styles.ts
  src/pages/Recover/index.tsx
Labels: Deploy

#186 Final countdown
  src/components/CreateUpGame/index.tsx
  src/components/Favorites/index.tsx
  src/components/Favorites/styles.tsx
  src/components/Game/index.tsx
  src/components/Menu/index.tsx
  src/components/Profiles/index.tsx
  src/components/TopRated/index.tsx
  src/contexts/AdminGamesContext.tsx
  src/contexts/ConfigUserContext.tsx
  src/contexts/FavoritesContext.tsx
  src/contexts/GamesContext.tsx
  src/contexts/ProfilesContext.tsx
  src/pages/Forgot/index.tsx
  src/pages/GamePage/index.tsx
  src/pages/Profile/styles.ts
  src/pages/Recover/index.tsx
  src/utils/validation.tools.ts
Labels: Deploy

#188 fix: deslike
  src/contexts/FavoritesContext.tsx
Labels: Bug

#190 fix: redirect to login
  src/pages/Recover/index.tsx
Labels: Fix

#194 Fix: type and sintax
  .eslintrc.js
  package.json
  src/pages/Recover/index.tsx
Labels: Deploy, Fix

#198 New version
  src/components/CreateUpGame/index.tsx
  src/components/Game/index.tsx
  src/components/Genres/styles.ts
  src/components/MenuUpdateChoice/index.tsx
  src/components/MenuUpdateUser/index.tsx
  src/pages/styles.ts
Labels: Fix

#199 fix: ts types and responsivity
  src/components/CreateUpGame/index.tsx
  src/components/Game/index.tsx
  src/components/Genres/styles.ts
  src/components/MenuUpdateChoice/index.tsx
  src/components/MenuUpdateUser/index.tsx
  src/pages/styles.ts
Labels: Fix

#207 Refactoring
  .eslintrc.js
  .prettierrc
  package.json
  src/assets/styles/global.ts
  src/components/Card/index.tsx
  src/components/Card/styles.tsx
  src/components/CreateUpGame/index.tsx
  src/components/Game/index.tsx
  src/components/Game/styles.tsx
  src/components/Gate/index.tsx
  src/components/Genres/index.tsx
  src/components/Input/index.tsx
  src/components/Menu/index.tsx
  src/components/Menu/styles.ts
  src/components/MenuDeleteUser/styles.ts
  src/components/MenuUpdateChoice/index.tsx
  src/components/MenuUpdateUser/index.tsx
  src/components/MenuUpdateUser/styles.ts
  src/components/Profile/index.tsx
  src/components/TopRated/index.tsx
  src/contexts/AccountContext.tsx
  src/contexts/AdminGamesContext.tsx
  src/contexts/ConfigUserContext.tsx
  src/contexts/FavoritesContext.tsx
  src/contexts/GamesContext.tsx
  src/contexts/OrderSettingsContext.tsx
  src/contexts/ProfilesContext.tsx
  src/contexts/index.tsx
  src/index.tsx
  src/pages/Forgot/index.tsx
  src/pages/GamePage/index.tsx
  src/pages/Recover/index.tsx
  src/utils/validation.tools.ts
Labels: Fix

#210 Fix: ajust background color
  .gitignore
  src/assets/styles/colors.ts
  src/pages/LoadingUser/index.tsx
  src/types/interfaces/system.ts
Labels: Deploy

#213 feat: search games
  src/components/Menu/index.tsx
  src/components/Menu/styles.ts
Labels: enhancement

#214 fix: hover search
  src/components/Menu/index.tsx
  src/components/Menu/styles.ts
Labels: Fix

#215 Fix: search
  src/components/Menu/index.tsx
  src/components/Menu/styles.ts
Labels: enhancement, Deploy

#217 Fix: layout width
  src/components/Favorites/styles.tsx
  src/components/TopRated/styles.tsx
Labels: Fix

#218 Fix: layout width
  src/components/Favorites/styles.tsx
  src/components/TopRated/styles.tsx
Labels: Deploy

#219 fix: update home layout
  src/assets/styles/global.ts
  src/components/Favorites/styles.tsx
  src/components/TopRated/styles.tsx
Labels: Fix

#224 fix: responsive search
  src/components/Menu/styles.ts
Labels: Fix
